# Copyright (C) 2018 The LineageOS Project

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),u1005)

include $(call all-makefiles-under,$(LOCAL_PATH))

include $(CLEAR_VARS)

NVDATA_MOUNT_POINT := $(TARGET_OUT_VENDOR)/nvdata
PROTECT_F_MOUNT_POINT  := $(TARGET_OUT_VENDOR)/protect_f
PROTECT_S_MOUNT_POINT := $(TARGET_OUT_VENDOR)/protect_s

$(NVDATA_MOUNT_POINT):
	@echo "Creating $(NVDATA_MOUNT_POINT)"
	@mkdir -p $(NVDATA_MOUNT_POINT)

$(PROTECT_F_MOUNT_POINT):
	@echo "Creating $(PROTECT_F_MOUNT_POINT)"
	@mkdir -p $(PROTECT_F_MOUNT_POINT)

$(PROTECT_S_MOUNT_POINT):
	@echo "Creating $(PROTECT_S_MOUNT_POINT)"
	@mkdir -p $(PROTECT_S_MOUNT_POINT)

ALL_DEFAULT_INSTALLED_MODULES += \
	$(NVDATA_MOUNT_POINT) \
	$(PROTECT_F_MOUNT_POINT) $(PROTECT_S_MOUNT_POINT) \

KERNEL_OUT := $(TARGET_OUT_INTERMEDIATES)/KERNEL_OBJ

$(KERNEL_OUT):
	mkdir -p $(KERNEL_OUT)

INSTALLED_KERNEL_HEADERS: $(KERNEL_OUT)

endif
